databricks_resources:
  catalog: main # change this to your catalog name
  schema: acl_demo # change this to your schema name
  chunked_data_table: chatbot_acl_chunked_data
  llm_endpoint_name: databricks-dbrx-instruct # optional(change this to your model endpoint name)
  vector_search_endpoint_name: one-env-shared-endpoint-15 # change this to your vector search endpoint name
  embedding_endpoint_name: databricks-gte-large-en
  vector_search_index: chatbot_acl_vs_index
  model_name: chatbot_with_acl
  chatbot_endpoint_name: chatbot_with_acl_endpoint
input_example:
  messages:
  - content: What is RAG?
    role: user
llm_config:
  llm_parameters:
    max_tokens: 1500
    temperature: 0.01
  llm_system_prompt_template: 'You are an assistant that answers questions. Use the
    following pieces of retrieved context to answer the question. Some pieces of context
    may be irrelevant, in which case you should not use them to form the answer.


    Context: {context}'
retriever_config:
  chunk_template: 'Passage: {chunk_text}

    '
  data_pipeline_tag: poc
  parameters:
    k: 5
    query_type: ann
  schema:
    chunk_text: chunked_text
    document_uri: path
    primary_key: chunk_id
  
